/**
 * Country scaffold — a developer-only generator for the *structure* of a new country dossier.
 *
 *   npm run scaffold:country -- --slug <slug> --name "<Country Name>" --code <ISO2> [--dry-run]
 *
 * ## What it does and, more importantly, does not
 *
 * It automates STRUCTURE, never TRUTH. It writes an unpublished skeleton (`status: 'research'`),
 * empty research/QA document templates, and a checklist. It writes NO source URL, NO statistic,
 * NO institutional claim, NO verification date, and NO route — every factual field is a `{{token}}`
 * or a `TODO`, which the publication gate and placeholder detector both reject. A scaffolded
 * country is unmistakably unfinished until a researcher replaces the skeleton with sourced content
 * and every publication condition passes. There is deliberately no `--publish` flag.
 *
 * The code validation is FORMAT only. `--code XZ` passes because it is two uppercase letters; the
 * scaffold does not and must not claim the code is a registered ISO 3166-1 alpha-2 country code —
 * that is a research question for the source register.
 *
 * The pure planner (`planScaffold`) is exported and unit-tested with a fictional fixture
 * (Exampleland / XZ) so the generator's guarantees are verified without ever writing a real file
 * or a real country into the tree.
 */
import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { register } from 'node:module';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

/* -------------------------------------------------------------------------- */
/* Input validation (format only)                                             */
/* -------------------------------------------------------------------------- */

const SLUG_RE = /^[a-z][a-z0-9]*(?:-[a-z0-9]+)*$/;
const CODE_RE = /^[A-Z]{2}$/;
const NAME_RE = /^[A-Z][A-Za-z.'’\- ]{1,60}$/;

export function validateScaffoldInput({ slug, name, code }) {
  const errors = [];
  if (!slug || !SLUG_RE.test(slug)) {
    errors.push(`slug "${slug ?? ''}" must be lowercase kebab-case (e.g. "new-zealand")`);
  }
  if (!code || !CODE_RE.test(code)) {
    errors.push(
      `code "${code ?? ''}" must be two uppercase letters (format only — not verified as ISO 3166-1)`,
    );
  }
  if (!name || !NAME_RE.test(name)) {
    errors.push(
      `name "${name ?? ''}" must be a plain country name beginning with a capital letter`,
    );
  }
  return errors;
}

/* -------------------------------------------------------------------------- */
/* Pure planner                                                               */
/* -------------------------------------------------------------------------- */

const constName = (slug) => slug.toUpperCase().replace(/-/g, '_');
const q = (s) => JSON.stringify(s); // always-valid TS string literal, escapes apostrophes

function dossierSkeleton({ slug, name, code }, moduleDefs) {
  const moduleStub = (def) =>
    `  {
    moduleId: ${q(def.id)},
    title: ${q(`${def.title} in ${name}`)},
    summary: ${q(`SCAFFOLD: TODO research ${def.title.toLowerCase()} in ${name}.`)},
    blocks: [],
    sources: [],
    status: 'draft',
    review: 'unreviewed',
    safetyReview: 'not-required',
    updatedOn: 'REPLACE-WITH-ISO-DATE',
    temporalScope: 'current',
    deferredReason:
      'TODO: research this module from primary sources, then set status to "published". {{remove-this-token}}',
  },`;

  return `import type { CountryDossier } from '../types';

/**
 * SCAFFOLD — ${name} has NOT been researched.
 *
 * Generated by scripts/scaffold-country.mjs. This is an unpublished skeleton: while status is
 * 'research' it produces no route, no sitemap entry and no navigation. Replace every {{token}}
 * and every TODO with content sourced from primary material, populate jurisdiction records and
 * sources, then follow the checklist the scaffold printed. Do NOT set status to 'published'
 * until \`validateCountryPublication\` returns no problems. Run prettier on this file after editing.
 */
export const ${constName(slug)}: CountryDossier = {
  countryCode: ${q(code)},
  slug: ${q(slug)},
  name: ${q(name)},
  // independentBodyNoun: 'a ${name} government body',  // TODO: uncomment and correct the demonym
  summary:
    'SCAFFOLD: ${name} has not been researched. TODO replace this dossier with sourced content before publication.',
  blocks: [
    {
      kind: 'callout',
      variant: 'note',
      title: 'Unresearched scaffold',
      text: 'TODO: research the justice system of ${name} from primary sources and replace this placeholder. {{remove-before-publishing}}',
    },
  ],
  sources: [],
  status: 'research',
  review: 'unreviewed',
  safetyReview: 'not-required',
  updatedOn: 'REPLACE-WITH-ISO-DATE',
  jurisdictionIds: [],
  modules: [
${moduleDefs.map(moduleStub).join('\n')}
  ],
};
`;
}

function researchPlanDoc({ slug, name, code }) {
  return `# ${name} — country research plan

> SCAFFOLD. Replace every TODO before publication.

- Country code (format only, verify as ISO 3166-1): ${code}
- Slug: ${slug}

## Jurisdiction scoping

TODO: is this a unitary state, a federation, or asymmetric? Which tiers do institutional work?

## Research questions

TODO: the specific questions this pilot must answer from sources.

## The model stress test

TODO: which part of the jurisdiction model does ${name} test? Does it need a new field, or is it
reuse? Default to reuse; add a field only with two independent forcing cases.

## Source hierarchy

TODO: the Tier-1 (constitution, codes, official gazette) and Tier-2 sources to read.
`;
}

function sourceRegisterDoc({ name }) {
  return `# ${name} — source register

> SCAFFOLD. Every row is a real, verified source or it is not published.

| id | title | publisher | url | verifiedOn | method | what it supports |
| -- | ----- | --------- | --- | ---------- | ------ | ---------------- |
| TODO | TODO | TODO | TODO | TODO | content-confirmed | TODO |

Do NOT record a source as verified unless its content was actually read and confirmed to say
what the citation claims. If an official site is WAF-blocked, record how it was retrieved.
`;
}

function modelFindingsDoc({ name }) {
  return `# ${name} — model findings

> SCAFFOLD. Record what the model already represented and any evidence-driven change.

## What reused cleanly

TODO.

## What needed a new field or value (if anything)

TODO — with the forcing case and why no existing value states it honestly. Prefer reuse.

## What stayed in prose

TODO — institution names, compositions, and one-off arrangements belong in prose, not schema.
`;
}

function qaDoc({ name }) {
  return `# ${name} — country pilot QA

> SCAFFOLD. Complete before publication.

- [ ] Every published module: sources ≥ 1, factsVerifiedOn set, review fact-checked, safety cleared.
- [ ] Deferred modules each carry a stated reason and no content.
- [ ] Restricted claims validate, or the claim is deferred (never a manufactured statistic).
- [ ] \`validateCountryPublication\` returns no problems.
- [ ] Adversarial verification of load-bearing constitutional/statutory facts.
- [ ] Browser + accessibility QA (desktop + mobile, keyboard, 320px, 200%).
`;
}

/**
 * Plan the scaffold without touching the filesystem. Returns the files it would write and the
 * next-step checklist, or a list of blocking errors. `existing` carries the current registries so
 * duplicates and route collisions are caught; it is injected (not imported) so the planner is
 * pure and unit-testable with synthetic input.
 */
export function planScaffold({ slug, name, code }, existing) {
  const {
    slugs = new Set(),
    codes = new Set(),
    routePaths = new Set(),
    moduleDefs = [],
  } = existing;

  const errors = validateScaffoldInput({ slug, name, code });

  const reservedSlugs = new Set([...moduleDefs.map((m) => m.slug), 'overview']);
  if (reservedSlugs.has(slug)) {
    errors.push(`slug "${slug}" collides with a reserved module slug`);
  }
  if (slugs.has(slug)) errors.push(`a dossier with slug "${slug}" already exists`);
  if (codes.has(code)) errors.push(`a country with code "${code}" already exists`);
  if (routePaths.has(`/countries/${slug}`)) {
    errors.push(`route /countries/${slug} already exists`);
  }

  if (errors.length > 0) return { ok: false, errors, files: [], checklist: [] };

  const files = [
    {
      path: `src/content/dossiers/${slug}.ts`,
      contents: dossierSkeleton({ slug, name, code }, moduleDefs),
    },
    {
      path: `docs/research/${slug}-research-plan.md`,
      contents: researchPlanDoc({ slug, name, code }),
    },
    { path: `docs/research/${slug}-source-register.md`, contents: sourceRegisterDoc({ name }) },
    { path: `docs/research/${slug}-model-findings.md`, contents: modelFindingsDoc({ name }) },
    { path: `docs/audits/${slug}-country-pilot-qa.md`, contents: qaDoc({ name }) },
  ];

  const checklist = [
    `Research ${name} from primary sources; fill the dossier skeleton and the four docs.`,
    `Add jurisdiction records for ${code} to src/content/jurisdictions.ts.`,
    `Add verified source records to src/content/sources.ts.`,
    `Set independentBodyNoun, updatedOn, factsVerifiedOn, and review on the dossier.`,
    `Register ${constName(slug)} in src/content/dossiers/index.ts (COUNTRY_DOSSIERS).`,
    `Add the planning entry for ${code} to src/content/countries.ts if not already present.`,
    `Add tests/content/countries-${slug}.test.ts and extend the dossier-slug guard in countries-france.test.ts.`,
    `Publish ONLY after \`validateCountryPublication\` returns no problems; there is no --publish shortcut.`,
  ];

  return { ok: true, errors: [], files, checklist };
}

/* -------------------------------------------------------------------------- */
/* CLI                                                                        */
/* -------------------------------------------------------------------------- */

function parseArgs(argv) {
  const args = { dryRun: false };
  for (let i = 0; i < argv.length; i += 1) {
    const a = argv[i];
    if (a === '--dry-run') args.dryRun = true;
    else if (a === '--slug') args.slug = argv[++i];
    else if (a === '--name') args.name = argv[++i];
    else if (a === '--code') args.code = argv[++i];
    else if (a === '--publish') {
      console.error(
        '✖ --publish is not a supported flag. Publication is a manual, reviewed step.',
      );
      process.exit(2);
    }
  }
  return args;
}

async function loadExisting(root) {
  register('./ts-resolve-hook.mjs', pathToFileURL(join(root, 'scripts/')));
  const load = (rel) => import(pathToFileURL(join(root, rel)).href);
  const [
    { COUNTRY_DOSSIERS },
    { COUNTRIES },
    { JURISDICTIONS },
    { PUBLIC_ROUTES },
    { COUNTRY_MODULES },
  ] = await Promise.all([
    load('src/content/dossiers/index.ts'),
    load('src/content/countries.ts'),
    load('src/content/jurisdictions.ts'),
    load('src/content/public-routes.ts'),
    load('src/content/country-modules.ts'),
  ]);
  return {
    slugs: new Set(COUNTRY_DOSSIERS.map((d) => d.slug)),
    codes: new Set([
      ...COUNTRY_DOSSIERS.map((d) => d.countryCode),
      ...COUNTRIES.map((c) => c.code),
    ]),
    routePaths: new Set([
      ...PUBLIC_ROUTES.map((r) => r.path),
      ...JURISDICTIONS.map((j) => j.id),
    ]),
    moduleDefs: COUNTRY_MODULES.map((m) => ({ id: m.id, slug: m.slug, title: m.title })),
  };
}

async function main() {
  const root = resolve(fileURLToPath(new URL('..', import.meta.url)));
  const args = parseArgs(process.argv.slice(2));

  const existing = await loadExisting(root);
  const plan = planScaffold(args, existing);

  if (!plan.ok) {
    console.error('✖ Cannot scaffold:');
    for (const e of plan.errors) console.error(`  - ${e}`);
    process.exit(1);
  }

  if (args.dryRun) {
    console.log(`Dry run — would create ${plan.files.length} file(s), writing nothing:\n`);
    for (const f of plan.files) console.log(`  + ${f.path}`);
    console.log('\nNext steps:');
    for (const c of plan.checklist) console.log(`  - ${c}`);
    console.log('\nRe-run without --dry-run to write these files.');
    return;
  }

  // No-clobber: never modify an existing file. Fail safely before writing anything.
  const clashes = plan.files.filter((f) => existsSync(join(root, f.path)));
  if (clashes.length > 0) {
    console.error('✖ Refusing to overwrite existing files (nothing was written):');
    for (const f of clashes) console.error(`  - ${f.path}`);
    process.exit(1);
  }

  for (const f of plan.files) {
    const abs = join(root, f.path);
    mkdirSync(dirname(abs), { recursive: true });
    writeFileSync(abs, f.contents, 'utf8');
    console.log(`  + ${f.path}`);
  }
  console.log(`\nScaffolded "${args.name}" as an UNPUBLISHED skeleton. Next steps:`);
  for (const c of plan.checklist) console.log(`  - ${c}`);
  console.log('\nIt produces no route until you research it and set status to published.');
}

const invokedDirectly =
  process.argv[1] && pathToFileURL(process.argv[1]).href === import.meta.url;
if (invokedDirectly) {
  main().catch((err) => {
    console.error(err);
    process.exit(1);
  });
}
